## Imports and data loading

In [17]:
import math
import random
import time

import pandas as pd
import numpy as np

from scipy import sparse
from scipy.sparse import csr_matrix
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics.pairwise import cosine_similarity

from sparselsh import LSH

## Content-based, regression

In [18]:
# load food.com data
directory = 'data/food.com'
df_recipe_rating = pd.read_csv(f'{directory}/recipe_ratings.csv')
df_recipe = pd.read_csv(f'{directory}/recipe.csv')

In [19]:
df_recipe.head()

,recipe_id,name,minutes,n_steps,n_ingredients,calories,fat,sugar,sodium,protein,saturated,carbs
0,137739,arriba baked winter squash mexican style,55,11,7,51.5,0.0,13.0,0.0,2.0,0.0,4.0
1,31490,a bit different breakfast pizza,30,9,6,173.4,18.0,0.0,17.0,22.0,35.0,1.0
2,112140,all in the kitchen chili,130,6,13,269.8,22.0,32.0,48.0,39.0,27.0,5.0
3,59389,alouette potatoes,45,11,11,368.1,17.0,10.0,2.0,14.0,8.0,20.0
4,44061,amish tomato ketchup for canning,190,5,8,352.9,1.0,337.0,23.0,3.0,0.0,28.0

In [20]:
df_recipe_rating

           user_id  recipe_id  rating
0             2046       4684     5.0
1             2046        517     5.0
2             1773       7435     5.0
3             1773        278     4.0
4             2046       3431     5.0
...            ...        ...     ...
698896      926904     457971     5.0
698897  2002312797      27208     5.0
698898     1290903     131607     5.0
698899      226867     363072     5.0
698900  2000498330     314535     5.0

[698901 rows x 3 columns]

In [21]:
#EXERCISE: Build a content-based recommender system that uses linear regression 
#          to predict ratings.
#          Try it out on users with a high number of ratings.
#          Try some train-test split to evaluate performance.

#select the ratings of a specific user 


sorted_users = df_recipe_rating.groupby(["user_id"]).agg(count=("user_id", "count")).sort_values("count", ascending=False)
target_id = sorted_users.index[0]
df_user = df_recipe_rating[df_recipe_rating['user_id']==target_id][['recipe_id','rating']]
df_rec = pd.merge(df_user, df_recipe, on='recipe_id', how='inner')



# define features
features = ["minutes", 
            "n_steps", 
            "n_ingredients", 
            "calories", 
            "fat", 
            "sugar",
            "sodium",
            "protein",
            "saturated",
            "carbs"
        ] 

# split training and test
x = df_rec.drop(["recipe_id" , "name"], axis=1)
y = df_rec["rating"]
x_train, x_test, y_train, y_test = train_test_split(x, y, shuffle=True)


model = LinearRegression();

predicted = model.fit(x_train, y_train).predict(x_test)


expected = []
for index, row in x_test.iterrows():
    expected.append(row['rating'])

mse = (np.square(expected - predicted)).mean()

print(f"mse:  {mse}")

# ...

mse:  3.2700507195907956e-31

## Content-based, KNN (with LSH)

In [22]:
directory = 'data/movielens/ml-latest-small'
#directory = 'data/movielens/ml-latest' #change into this one for the full dataset (slow)

df_movies = pd.read_csv(f'{directory}/movies.csv')
df_ratings = pd.read_csv(f'{directory}/ratings.csv')
df_tags = pd.read_csv(f'{directory}/tags.csv')

#transform tags such that they are lower-case, single-word tokens
df_tags['tag'] = df_tags['tag'].apply(lambda x: str(x).lower().replace(' ', '_'))

In [23]:
df_movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [24]:
df_tags.head()

   userId  movieId              tag   timestamp
0       2    60756            funny  1445714994
1       2    60756  highly_quotable  1445714996
2       2    60756     will_ferrell  1445714992
3       2    89774     boxing_story  1445715207
4       2    89774              mma  1445715200

### Step1: Calculate item profiles

In [25]:
# calculates the lexicon of most frequent tags.
tag_frequency_threshold = 5 # increase number to filter
# sorted_users = df_recipe_rating.groupby(["user_id"]).agg(count=("user_id", "count")).sort_values("count", ascending=False)
df_lexicon = df_tags.groupby("tag").agg(count=("tag", "count")) # get a dataframe with tags and respective counts
# discard movies with no tags
item_profiles = df_movies[df_movies["movieId"].isin(df_tags["movieId"])]
item_profiles
# you can drop the userId and timestamp columns because we don't care who assigned the tag and when
# ...

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
4,5,Father of the Bride Part II (1995),Comedy
6,7,Sabrina (1995),Comedy|Romance
...,...,...,...
9681,183611,Game Night (2018),Action|Comedy|Crime|Horror
9692,184471,Tomb Raider (2018),Action|Adventure|Fantasy
9709,187593,Deadpool 2 (2018),Action|Comedy|Sci-Fi
9710,187595,Solo: A Star Wars Story (2018),Action|Adventure|Children|Sci-Fi
9732,193565,Gintama: The Movie (2010),Action|Animation|Comedy|Sci-Fi

In [26]:
#calculate the sparse feature vector based on the TF-IDF of words in documents
#the TF-IDF vectors are saved as sparse representations into the dataframe
df_features = df_tags.groupby('movieId').agg(lambda x: ' '.join(x)).reset_index()
vectorizer = TfidfVectorizer(tokenizer=lambda x: x.split(' ')).fit(sorted(df_features['tag']))
vectorizer.vocabulary_
df_features['feature_vector'] = df_features['tag'].apply(lambda x : vectorizer.transform([x]))
df_features

/var/folders/m5/l9b6fpv12v370f32ct4y00h00000gn/T/ipykernel_7469/2621643708.py:3: FutureWarning: ['userId', 'timestamp'] did not aggregate successfully. If any error is raised this will raise in a future version of pandas. Drop these columns/ops to avoid this warning.
  df_features = df_tags.groupby('movieId').agg(lambda x: ' '.join(x)).reset_index()
/Users/alexanderwermuth/opt/anaconda3/envs/data-in-production/lib/python3.10/site-packages/sklearn/feature_extraction/text.py:528: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(

,movieId,tag,feature_vector
0,1,pixar pixar fun,"(0, 1016)\t0.8992312620852461\n (0, 513)\t0..."
1,2,fantasy magic_board_game robin_williams game,"(0, 1129)\t0.48431677463057304\n (0, 812)\t..."
2,3,moldy old,"(0, 967)\t0.7071067811865475\n (0, 876)\t0...."
3,5,pregnancy remake,"(0, 1106)\t0.6808321878901952\n (0, 1044)\t..."
4,7,remake,"(0, 1106)\t1.0"
...,...,...,...
1567,183611,comedy funny rachel_mcadams,"(0, 1084)\t0.7153847877740599\n (0, 515)\t0..."
1568,184471,adventure alicia_vikander video_game_adaptation,"(0, 1418)\t0.6173008972335793\n (0, 46)\t0...."
1569,187593,josh_brolin ryan_reynolds sarcasm,"(0, 1156)\t0.5453455400986055\n (0, 1147)\t..."
1570,187595,emilia_clarke star_wars,"(0, 1266)\t0.6876494487057803\n (0, 433)\t0..."
1571,193565,anime comedy gintama remaster,"(0, 1107)\t0.5715745894656075\n (0, 536)\t0..."

### Step2: Index item profiles into LSH

In [27]:
m = sparse.vstack(df_features["feature_vector"])
#index all item vectors into LSH
lsh = LSH(4, m.shape[1], num_hashtables=1, storage_config={"dict":None})
#run an example query to the LSH
lsh.index(m, df_features["movieId"])
query = np.zeros(m.shape[1])
query[0] = 1
lsh.query(csr_matrix(query))

[((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 3 stored elements in Compressed Sparse Row format>,
   150),
  1.9999999999999996),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 7 stored elements in Compressed Sparse Row format>,
   38061),
  1.9999999999999996),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 3 stored elements in Compressed Sparse Row format>,
   176419),
  1.9999999999999998),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 4 stored elements in Compressed Sparse Row format>,
   111743),
  1.9999999999999998),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 9 stored elements in Compressed Sparse Row format>,
   87430),
  1.9999999999999998),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 2 stored elements in Compressed Sparse Row format>,
   2431),
  1.9999999999999998),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 4 stored elements in Compressed Sparse Row format>,
   8961),
  1.9999999999999998),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   6963),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   6970),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   7023),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   7025),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   7071),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   7088),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   7121),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   7141),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   7218),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   6786),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   7234),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   7439),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   7700),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   7748),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   7792),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   7924),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   7926),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   8014),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   7190),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   6773),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   6713),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   6724),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   4969),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   5120),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   5224),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   5238),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 3 stored elements in Compressed Sparse Row format>,
   5291),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   5304),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   5475),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   5498),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   5633),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   5747),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   6027),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   6041),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 2 stored elements in Compressed Sparse Row format>,
   6157),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   6228),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   6244),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   6452),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   6466),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   6516),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   6660),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   6668),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   8033),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   6744),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   8094),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   8197),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   8190),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   32160),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   32371),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   34437),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   34482),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   36535),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   37240),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   37733),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 2 stored elements in Compressed Sparse Row format>,
   39234),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   40583),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   31923),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   40629),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   42002),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   42740),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 7 stored elements in Compressed Sparse Row format>,
   45730),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 3 stored elements in Compressed Sparse Row format>,
   58295),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 2 stored elements in Compressed Sparse Row format>,
   62434),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 8 stored elements in Compressed Sparse Row format>,
   69757),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   82242),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 6 stored elements in Compressed Sparse Row format>,
   119141),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 2 stored elements in Compressed Sparse Row format>,
   126548),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   41997),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 3 stored elements in Compressed Sparse Row format>,
   30892),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   27741),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   27731),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   4787),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   8207),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   8275),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   8337),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   8379),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   8507),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   8607),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   8609),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   8638),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   8754),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   8765),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   8838),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   8920),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   8943),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   8998),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   25855),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   25865),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   25952),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   26131),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   26242),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   26776),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   8183),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   4688),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 2 stored elements in Compressed Sparse Row format>,
   3),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   4477),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   1041),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 2 stored elements in Compressed Sparse Row format>,
   1084),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   1135),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 2 stored elements in Compressed Sparse Row format>,
   1147),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 2 stored elements in Compressed Sparse Row format>,
   1178),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   1185),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   1204),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   1277),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   1280),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 2 stored elements in Compressed Sparse Row format>,
   1301),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   1361),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   1398),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 2 stored elements in Compressed Sparse Row format>,
   1441),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   1446),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   1542),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   1586),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 2 stored elements in Compressed Sparse Row format>,
   1643),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   1650),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   1663),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   1672),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   1674),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   976),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   1683),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   930),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   800),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 8 stored elements in Compressed Sparse Row format>,
   32),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   111),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   160),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   162),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   215),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 2 stored elements in Compressed Sparse Row format>,
   224),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   232),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   246),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   261),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   279),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   290),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   326),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 2 stored elements in Compressed Sparse Row format>,
   425),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   474),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   516),
  2.0),
 ((<1x1475 sparse matrix of type '<class 'numpy.float64'>'
   	with 1 stored elements in Compressed Sparse Row format>,
   529),
  2.0),

### Step 3: Calculate user profile

In [28]:
# restricts the ratings to the set of most popular movies (optional, not needed for content-based)
numratings_threshold = 0 #increase this number if you want to filter
df_item_popularity = df_ratings[['movieId','rating']].groupby('movieId').count().reset_index()
df_item_popularity.columns = ['movieId','count'] 
df_item_popularity = df_item_popularity.sort_values(by='count', ascending=False)
df_item_popularity = df_item_popularity[df_item_popularity['count'] >= numratings_threshold]
print(f'Number of movies reduced from {len(df_ratings.movieId.unique())} to {len(df_item_popularity.movieId.unique())}')
df_ratings = pd.merge(df_ratings, df_item_popularity, on='movieId', how='inner')[['userId', 'movieId', 'rating']]
df_ratings = df_ratings.sort_values(by='userId')

#rescale the ratings by the user's individual average 
df_ratings['rating_scaled'] = ...

df_ratings.head()

Number of movies reduced from 9724 to 9724

       userId  movieId  rating rating_scaled
0           1        1     4.0      Ellipsis
12117       1     2389     2.0      Ellipsis
12126       1     2395     5.0      Ellipsis
12182       1     2406     4.0      Ellipsis
776         1       70     3.0      Ellipsis

In [29]:
# join ratings with movie feature vectors
df_profile = pd.merge(df_ratings, df_features[['movieId','feature_vector']],
              on='movieId')
#scaling feature vector by rating (this will take a few minutes)
df_profile['feature_vector_scaled'] = df_profile['rating_scaled'] * df_profile['feature_vector']
df_profile

TypeError: unsupported operand type(s) for *: 'float' and 'ellipsis'

In [ ]:
start = time.time()
#stack all sparse vectors of user's movies
df_user_vectors = df_profile[['userId', 'feature_vector_scaled']].groupby('userId').agg(sparse.vstack).reset_index()
#compute the average of the vectors without considering the zero entries (this will take a while)
df_user_vectors['feature_vector_scaled'] = df_user_vectors['feature_vector_scaled'].apply(lambda x: csr_matrix(np.nan_to_num(x.sum(axis=0)/x.getnnz(axis=0), 0)))
end = time.time()
print(end - start)
df_user_vectors

### Step 4: Rank potential recommendation candidates

In [ ]:
#pick a target user to provide recommendations to
idx = 42
target_userId = df_user_vectors.iloc[idx].userId

In [ ]:
#get user rating history
df_user_history = ...

#select candidate recommendations to user
df_recommendation = ...

In [ ]:
df_recommendation

In [ ]:
df_user_history.head(10)

In [ ]:
df_user_history.tail(10)

### Step 5: Predict ratings of candidate items

In [ ]:
#index all user vectors into LSH
df_usr = df_profile[df_profile['userId'] == target_userId]
lsh_usr = LSH(...)
lsh_usr.index(..., extra_data=[...]) # repeat for all users. Insert movieid and rating as extra data for future retrieval
lsh_usr

In [ ]:
# compute recommendation
df_recommendation = ...

## Collaborative filtering

In [ ]:
from surprise import SVD
from surprise import Reader
from surprise import Dataset
from surprise.model_selection import cross_validate
from surprise.prediction_algorithms.knns import KNNBasic

In [ ]:
directory = 'data/movielens/ml-latest-small'
#directory = 'data/movielens/ml-latest' #change into this one for the full dataset (slow)
df_ratings = pd.read_csv(f'{directory}/ratings.csv')
df_ratings.head()

In [ ]:
# initialize a data reader
reader = Reader(rating_scale=(1, 5))
# provide a dataset with userid, itemtid, and rating in order
data = Dataset.load_from_df(df_ratings[['userId','movieId','rating']], reader)

# surprise has also some built-in datasets that can be imported directly
#data = Dataset.load_builtin('ml-100k')

In [ ]:
# initialize a user-based K nearest neighbors implementation
anti_set = data.build_full_trainset().build_anti_testset()
anti_set

# execute 5-fold cross-validation and measure RMSE and MAE
# ...

NameError: name 'data' is not defined